### PR TITLE
Add button to reset all settings

### LINKED ISSUE #236: Feature: Add a way to reset all settings
As @pitts-mo discovered while testing pr #222 , currently, when updating the goggles, the old config file is always retained. 
When changes are made to the way the goggle handles settings, like with this recently merged pr #196 , retaining the old config file may have unintended consequences.

If I understand it correctly, a backup copy of the existing config file is made by [update_goggle.sh](https://github.com/hd-zero/hdzero-goggle/blob/a29cfcd692102f0d41329b41207d367830f22cae/mkapp/app/script/update_goggle.sh#L120) during the update process.
During startup, the function [settings_load](https://github.com/hd-zero/hdzero-goggle/blob/a29cfcd692102f0d41329b41207d367830f22cae/src/core/settings.c#L183) in settings.c then checks for the existence of that backup and, if it exists, replaces the actual config file with the backup and then deletes the backup.

Before the next release we should at least add a convenient way for the user to reset all settings, and possibly a way to automatically perform a settings reset during the update process if needed.

### PR DESCRIPTION
**Pull request by Nikolas-S**
Added a button to reset all settings to the Firmware page.
The button deletes the ini settings file, creates a new (empty) one, and writes the current version of the settings file to it.
Also added a new APP_STATE that blocks all user input, for example for when the user has to repower the goggles.
During startup, the version of the settings file is checked against the expected version and, if they're not the same, the settings are reset. This could be expanded to migration in the future.
With this it should also be possible to go back to older versions by resetting the settings right before updating.

Closes #236 

reset_btn

reboot_reset

Also added the new popup to the goggle update process, blocking input and prompting the user to repower.
reboot_update

### CODE REVIEW

**Comment by Nikolas-S** [comment]
Would appreciate it if someone could give this a test on their goggles, don't have mine on me atm.

**Comment by Nikolas-S** [comment]
I created a test [branch](https://github.com/Nikolas-S/hdzero-goggle/tree/test/setting_reset_osd_element_pos) on my fork, based on the current main, that has #222 and this pr merged.
@pitts-mo If you have the time, would you mind testing the branch and after changing the osd element positions, use the reset button just before going back to 9.0.12? https://github.com/Nikolas-S/hdzero-goggle/actions/runs/5043798284
Hopefully the osd elements will be ok when going back to 9.0.12.

**Comment by pitts-mo** [comment]
This was already my first priority when my goggles return from optic replacement. ETA within next couple days? I will verify 9.0.12 is still installed and build this PR for SD card. :-) 
Thank you,
-p

**Comment by ligenxxxx** [comment]
It would be nice if the edge of the pop-up window is red so that we can keep the UI style consistent.

**Comment by Nikolas-S** [comment]
Was going with green initially to indicate ok/warn/error but trying it with red, I think you're right, fits better.
border_red_text_green

But I do think we should keep using the title color to indicate outcome, examples for warn/error:
border_red_text_yellow
border_red_text_red

**Comment by pitts-mo** [comment]
@Nikolas-S 
So far the settings reset appears to work as expected. I performed a reset and booted to 9.0.12 and was able to regain the old OSD functionality. I performed another reset test after returning to this PR without issue.

However, I notice a three odd characters keep getting appended onto the APP section of the Current Version display. The characters appear random for each boot session and persist until power cycle.

**Comment by Nikolas-S** [comment]
@pitts-mo 
Thank you for testing!
I found a possible issue with how the version is read from file, when you have time, please let me know if the issue persists.
If it does, please add an example of what exactly your version says.

**Comment by pitts-mo** [comment]
Resolved.
I no longer observe erroneous characters appended to the APP version or anywhere else within the Current Version string.
Thank you,
-p

**Pull request merged**
