### PR TITLE
Starred DVR

### PR DESCRIPTION
**Pull request by qvasic**
## Ability to add "stars" to your DVRs.

Useful feature to mark time on your DVR files: if landed a cool trick, flown your fastest lap or crashed somewhere far - just press a configured button so goggles save a "star" on your DVR, which you can later see on Playback page and in DVR player, or on filesystem of your SD card later when you edit your videos.

## How to use it:

Go into Input menu, and assign "Star DVR" to an input of your choice:

hdzero-stars-1

While DVR is being recorded activate that input (e.g. click the right button) - a file is created next to the DVR file which is currently being recorded, time stamp in format "minutes:seconds" is appended to that file:

image

Go to Playback menu - files which has "star" file next to them will be marked with yellow star icon:

hdzero-stars-2

Play a DVR file with a star icon - "stars" will be shown on the timeline (up to 10 stars):

hdzero-stars-3

### CODE REVIEW

**Comment by MichelleRos** [comment]
Cool idea! This looks really useful. 
You could change the heart/like to a star if you want it a bit more applicable for crashes etc as well :) 
How did you get the heart image though?

**Comment by qvasic** [comment]
> Cool idea! This looks really useful. You could change the heart/like to a star if you want it a bit more applicable for crashes etc as well :)
Thanks! Yes, "star" might be more applicable to more circumstances. :)

> How did you get the heart image though?
I've just written a Python script which generated required C code from picture's ASCII drawing. :)

**Comment by qvasic** [comment]
I've finally got some time to finish this.
I've changed feature name and icon, cleaned-up the code.
It is ready for review @ligenxxxx .

**Comment by ligenxxxx** [comment]
@qvasic I found in actual use that when I was in video mode and started to star dvr, I couldn't tell whether the operation was successful. My suggestion is to add a new [REC] OSD that contains a ⭐ in the lower right corner. Show it when staring.

**Comment by qvasic** [comment]
> @qvasic I found in actual use that when I was in video mode and started to star dvr, I couldn't tell whether the operation was successful. My suggestion is to add a new [REC] OSD that contains a ⭐ in the lower right corner. Show it when staring.

Sounds useful. I'll get to it when I have time.

**Pull request merged**
