### PR TITLE
OLED burnin and static image protection

### PR DESCRIPTION
**Pull request by SumolX**
Performs two levels of orbiting the OSD in order to minimize screen burn-in and static image retention.

image

### CODE REVIEW

**Comment by SumolX** [comment]
Noticed some graphical anomalies when switching between live and menu.... setting PR to draft.

**Comment by stefan74xxx** [comment]
@SumolX: Just a small question - does this orbit-function "only" work on HDZero-ui elements or although for the BetaFlight  ones (like battery voltage)? Because the last ones will although "burn in" after some time. Sorry, tried to understand the code, but not fully sure...

**Comment by stefan74xxx** [comment]
Thanks for the response! Will see if i can successfully compile a firmware and give it a shot ...

**Comment by stefan74xxx** [comment]
Hi - just an update: HDZero and BetaFlight OSD elements are moved by the orbit function - as expected by your explanation.

Another idea to reduce the OLED burnin problem even more "OLED burnin: Change color of OSD-elements in Google Menu" as issue #383

**Pull request merged**
