### PR TITLE
Double click right button to reset HT centre point

### PR DESCRIPTION
**Pull request by pkendall64**
Implements a double-click handler for the right button (when in video mode) that resets the centre position of the head tracker.

The second commit is a code reformat only.

### CODE REVIEW

**Comment by bkleiner** [comment]
Code LGTM

let's cut this into 8.0.0, reading Yith's experience in the original PR this feels necessary for real-world operation to me.
maybe @Yith1 can give it try (including testing the non-doubleclick operation of the right button) and report back.

**Comment by Yith1** [comment]
Is this for wireless, wired, or both?
Note I won't actually be able to get out flying this weekend, but can try this out in the goggles at some point.

**Comment by pkendall64** [comment]
> Is this for wireless, wired, or both? Note I won't actually be able to get out flying this weekend, but can try this out in the goggles at some point.

This is for both.

**Comment by Yith1** [comment]
Ok, so ideally testing needs to be both as well I guess. I suspect there will be need for two different goggle firmwares for these?

**Comment by bkleiner** [comment]
> Is this for wireless, wired, or both? Note I won't actually be able to get out flying this weekend, but can try this out in the goggles at some point.

Technically this PR is for both, but seeing i would like to get it merged for 8.0.0,
lets eliminate the variable of wireless (planned for 8.1.0) for now.
https://github.com/hd-zero/hdzero-goggle/actions/runs/4139169265

**Comment by Yith1** [comment]
Ok.. it bench tests just fine for wired headtracking. Nice double-click speed. Immediate recentering. 

All good.

**Comment by Yith1** [comment]
I used the firmware attached to the action. For the wireless I'd need a different set, from a PR including the wireless functionality, right?

**Comment by Yith1** [comment]
Ah, got to test non-double click as well... BRB!

**Comment by Yith1** [comment]
Ok, long click changes fan speed still. 

Short click stops recording and it immediately starts again. I guess that bug has not been fixed?

**Comment by bkleiner** [comment]
technically not a bug....just very unfortunate, but intended, behaviour :P 

good, let's get this merged, that will allow @pkendall64 to rebase the wireless PR again.

**Comment by Yith1** [comment]
> good, let's get this merged, that will allow @pkendall64 to rebase the wireless PR again.

Let me know when it's rebased. I'd like to get the wireless back on my goggles... just in case I do get to go flying. ;)

**Pull request merged**
