### PR TITLE
Add extended and transparent fonts for Kiss Ultra

### PR DESCRIPTION
**Pull request by KissUltra**
Add Extended and Transparent font for Kiss ULTRA

### CODE REVIEW

**Comment by bkleiner** [comment]
does this deprecate the existing font at https://github.com/hd-zero/hdzero-goggle/blob/main/mkapp/app/resource/OSD/FC/UTRL_000.bmp ?

**Comment by KissUltra** [comment]
yes, its new version.

**Comment by KissUltra** [comment]
It has 2 pages and transparency :)

**Comment by bkleiner** [comment]
do we need a transition period or can the old font be removed immeditatily?

**Comment by bkleiner** [comment]
for consistency i do recommend that the font is submitted to https://github.com/hd-zero/hdzero-osd-font-library as well. that will allow VRX users to download it and allow goggles users to use the font without updating their firmware first.

**Comment by KissUltra** [comment]
I know, but since its for ULTRA only, i keep all fonts on ULTRA wiki. Its NOT compatible with BF, so i rather have it in same place. ;) I had grace period of 5 releases to let pilots use SD card fonts, looks like now everyone updated - time to commit to HD systems fw.

**Comment by bkleiner** [comment]
your call on how you want to handle distribution, but is that a yes on the immediate removal of the old font?

**Comment by KissUltra** [comment]
Its a replacement font. same name, isnt it? Yes, new one should go in place of old one. Ligen already made me test build so we will test it tonight on googles.

**Comment by bkleiner** [comment]
no, they have slightly different naming: https://github.com/hd-zero/hdzero-goggle/tree/main/mkapp/app/resource/OSD/FC
`UTRL_000.bmp` always seemed like a typo to me, but i dont have any Kiss gear to verify.

**Comment by KissUltra** [comment]
CRAP!!!!!

**Comment by KissUltra** [comment]
So, new file stays, old file can be deleted.

**Comment by KissUltra** [comment]
You are the best. Thank you!

**Pull request merged**
