### PR TITLE
Offload beep to new thread, make audible.

### PR DESCRIPTION
**Pull request by Knifa**
This PR moves beep GPIO control to a separate thread so that beeps don't block and so can be made long enough to be audible. 😄 Calling parts of the system don't need to worry about it waiting anymore.

- The previous beep (via `beep()`) is only 500us (!) so just makes a little tap sound. The default beep is now 50ms, with a longer 200ms beep available for future use.
- `beep_dur` now takes milliseconds, rather than microseconds.

### CODE REVIEW

**Comment by Knifa** [comment]
Paired with #258, for example! Used `beep_dur(1)` on this for some satisfying little taps. No blocking!
https://github.com/hd-zero/hdzero-goggle/assets/622619/1e2b63f5-648d-49c5-a1de-3428ae15046f

**Comment by Knifa** [comment]
Moved some stuff around so the thread only needs to lock the mutex once.

**Comment by SumolX** [comment]
I've never noticed that there was supposed to be an audible sound outside the clicking of the scroll wheel.  Nice job!

**Comment by ligenxxxx** [comment]
Not everyone likes the buzzer beeping when scrolling the scroll wheel. How should we meet different user needs?

**Comment by Knifa** [comment]
> Not everyone likes the buzzer beeping when scrolling the scroll wheel. How should we meet different user needs?

This isn't included in the PR. Just an example of how the beep can work now that it doesn't block the thread.

**Comment by ligenxxxx** [comment]
It is wise to implement the buzzer in a separate thread.
Also, I suggest moving beep related functionality to beep.c. Because I have extra ideas to enrich the interface and control of beep, so that it can even play some simple 8bit music.

**Pull request merged**
