### PR TITLE
optimize 1080p display

### PR DESCRIPTION
**Pull request by ligenxxxx**
To optimize:
- HDZero 1080P30 OSD
- HDMI in 1080P60

### CODE REVIEW

**Comment by pitts-mo** [comment]
1080p60 is a priority and the EDID modes list should be limited. But, As a person who can not budget for a good sim/gaming graphics card I find it desirable to present at least some key/common lower resolution and lower refresh modes within EDID data.


9.2.0-rc1 only presents EDID for these two video modes to linux:
   1920x1080     50.00*+  50.00  
   1280x720     100.00    60.00    60.00    59.94  

9.1.0 and older builds were reporting EDID for these modes:
   1920x1080     60.00 +  59.94  
   1920x1080i    60.00    59.94  
   1600x1200     60.00  
   1680x1050     59.88  
   1280x1024     75.02    60.02  
   1440x900      74.98    59.90  
   1280x960      60.00  
   1280x800      59.91  
   1152x864      75.00  
   1280x720      60.00    59.94  
   1024x768      75.03    70.07    60.00  
   832x624       74.55  
   800x600       72.19    75.00    60.32  
   720x480       60.00    59.94  
   640x480       75.00    72.81    66.67    60.00    59.94  
   720x400       70.08

**Comment by pitts-mo** [comment]
I realize my last comment is not directly related to this PR. And I do not know what modes are desirable for average users. I just wanted to make sure the thought was considered while you are working in the same area. Thank you, -p

**Comment by ligenxxxx** [comment]
> 1080p60 is a priority and the EDID modes list should be limited. But, As a person who can not budget for a good sim/gaming graphics card I find it desirable to present at least some key/common lower resolution and lower refresh modes within EDID data.
> 
> 9.2.0-rc1 only presents EDID for these two video modes to linux: 1920x1080 50.00*+ 50.00 1280x720 100.00 60.00 60.00 59.94
> 
> 9.1.0 and older builds were reporting EDID for these modes: 1920x1080 60.00 + 59.94 1920x1080i 60.00 59.94 1600x1200 60.00 1680x1050 59.88 1280x1024 75.02 60.02 1440x900 74.98 59.90 1280x960 60.00 1280x800 59.91 1152x864 75.00 1280x720 60.00 59.94 1024x768 75.03 70.07 60.00 832x624 74.55 800x600 72.19 75.00 60.32 720x480 60.00 59.94 640x480 75.00 72.81 66.67 60.00 59.94 720x400 70.08
Prior to 9.2.0, I believe only 1080p and 720p displayed properly, although many resolutions would be displayed.
It is difficult for Goggle to support all hdmi in resolutions (resources are scarce), so we have configured and enabled edid since 9.2.0. In this way, there will be no problem that the display cannot be displayed after the user selects a resolution.
Of course, some hdmi hosts may not support edid, that's another matter.

**Comment by ligenxxxx** [comment]
> I realize my last comment is not directly related to this PR. And I do not know what modes are desirable for average users. I just wanted to make sure the thought was considered while you are working in the same area. Thank you, -p
> 
> I have added some common modes and requested others to provide feedback in discord: https://discord.com/channels/880782999006883870/880801151539347467/1141774223262613617

Prior to 9.2.0, I believe only 1080p and 720p displayed properly, although many resolutions would be displayed.
It is difficult for Goggle to support all hdmi in resolutions (resources are scarce), so we have configured and enabled edid since 9.2.0. In this way, there will be no problem that the display cannot be displayed after the user selects a resolution.
Of course, some hdmi hosts may not support edid, that's another matter.

This PR is mainly used to solve the problem of unclear OSD display and glitch at 1080p resolution.

**Comment by MartinHugh** [comment]
May be related to https://github.com/hd-zero/hdzero-goggle/issues/316

**Comment by RecifeStargazer** [comment]
Tested with ws vrx. 720p60 is now smooth, but 1080p60 most of time black, flickering sometimes to show video

**Comment by ligenxxxx** [comment]
@RecifeStargazer 
Please check if the same thing happens when using PC 1080P60 as source.
Also, Can you test 1080P50?

**Comment by FlackMonkey** [comment]
@ligenxxxx 
Checked now in two setups:

1.  Via adapter -> PC. Works Good. On 9.1.0 and 9.2.0 - it used to have artidacts based on overall colors on screen 
2. With Walksnail VRX (FW 34.40.15). Image has no artifacts (as it was on (9.1.0 and 9.2.0), but whole image dissapears (black screen) randomly within 2-8sec intervals and appears again. Changing hdmi cable doesn't affect issue

Feel free to reach me out for more testing. Thanks!

**Pull request merged**
