### PR TITLE
Send MSP to backpack when channel is changed for HDZero

### PR DESCRIPTION
**Pull request by cruwaller**

### CODE REVIEW

**Comment by cruwaller** [comment]
First approach was a bit rude and decided to move it under ELRS menu.

**Comment by cruwaller** [comment]
rebased on main.

**Comment by HazzaHFPV** [comment]
So, how does this work, what does it do? I see the entry in the menu, but it doesnt do anything..or i am not understanding it.

**Comment by cruwaller** [comment]
Functionality is on the way and this allows to set VTX channel from the goggles.

**Pull request merged**
