### PR TITLE
Add date-based naming scheme for DVR files and add video metadata

### LINKED ISSUE #42: Feature request: Improve the DVR filename convention
Please change the video files naming convention for something like `2023-01-24 16h46 HDZ_0042.ts` (in the VRX as well), so that the files could be ordered chronologically (alphabetically), even if they come from multiple HDZero goggle (which would then not have the same index counter).

Also, make sure the extension is `.ts`, not the uppercase `.TS`.

### LINKED ISSUE #116: Feature request: Support timestamp in DVR metadata
As discussed by @rquellet in [this YouTube video](https://www.youtube.com/watch?v=p4qXiQrtCkU&t=443s) there is a RTC in the goggles.
Having this information in the DVR files is essential for me and allows easier management of flight footage.

See #123 for details on implementation.

### PR DESCRIPTION
**Pull request by Master92**
This PR allows users with an active RTC to chose between the conventional naming scheme (i.e. hdz_000, hdz_001 etc.) and a date-based one (i.e. 2023-11-24T13_34_37).
When no rtc battery is present, the user can not change the naming scheme. On top of that, it automatically falls back to the conventional scheme as default.

Further, I added some metadata to the DVR files i.e. a title (currently the file name) and - for mp4 - the date it was created.
Over the course of my research and the implementation, I found out that the ts container does not support any metadata information about the media creation date, hence a note in the sources.

Closes #42
Closes #116

### CODE REVIEW

**Comment by SumolX** [comment]
I was playing with this feature on the emulator and noticed I'm unable to change the Naming Scheme option because there is no RTC battery installed on the Emulator.  Do you think this option should be be disabled in a similiar fashion to your other PR, if no RTC battery is present then the row is not selectable and has a darker shade?

Perhaps mark the PR as a draft until the other PR has been merged, that way it follows the standard you have set forth.

**Comment by Master92** [comment]
> I was playing with this feature on the emulator and noticed I'm unable to change the Naming Scheme option because there is no RTC battery installed on the Emulator. Do you think this option should be disabled in a similar fashion to your other PR, if no RTC battery is present then the row is not selectable and has a darker shade?

You're right. I already had that in mind but wasn't sure how to correctly go ahead and mark this PR to lack some work after #369. I'll convert this PR to draft in a minute 👍 
Maybe I'll play around a little and try to come up with an RTC mock for emulator builds 😉 

> Actually I could see us temporary blinking the Date/Time in live view when the recording is started.... that way we don't need to have it on permanently.... but that would potentially be a future feature.

Yeah we should keep that in mind. Perhaps you'd need the user to decide how they want the OSD to behave.

> Final comment... though its more of a personal preference.... i think we should simplify the timestamp convention to something a little more readable perhaps...
> 
> 2023-11-24T13_34_37.mp4 to 20231124_133437.mp4

That's actually a good idea imho. That way you could navigate your files easier by just typing the digits instead of having to add the dashes, too. The only thing I'd change is separating the date from time with a dash instead of an undesrscore like so: `20231124-133437.mp4`. What do you think about that?
I came up with the current scheme through [Wikiwix's comment](https://github.com/hd-zero/hdzero-goggle/issues/123#issuecomment-1466990455) in #123.

**Comment by Master92** [comment]
That was a pure coincidence, they aren't on my (German) keyboard 😆

**Comment by evilC** [comment]
Liking it, great!  
Any thoughts, however, on #359 ?

**Comment by evilC** [comment]
It's worth noting that it appears that this PR also changed hot clip naming?  (At least I assume it was this PR, I see that `mark_video_file` changed.  
Previously, if you had no hot clips and hot clipped DVR file `hdz_028`, it would become `hot_hdz_001`, but now it becomes `hot_hdz_028`.  
I kind of like it to be honest, it helps you know where the file was in the sequence of DVR files - without the RTC mod, this was impossible to know for sure with the old system.  
It also seems that the next clip will be `hdz_029` - ie `hdz_028` would not get used again, so you would not end up with a `hot_hdz_028` and a `hdz_028`, so even if this was unintentional, I see no real need to change it back to how it was.

**Comment by Master92** [comment]
That was indeed unintentional 😅

**Comment by evilC** [comment]
@Master92 If we do intend to keep it as it currently is, then we should probably remove [unused code](https://github.com/hd-zero/hdzero-goggle/blob/main/src/ui/page_playback.c#L322)

**Comment by Master92** [comment]
@evilC agreed. I'm currently working on that file for the date-folder feature and will try to keep removing that in mind 👍

**Comment by evilC** [comment]
@Master92 I could maybe get rid of it as part of PR #389 ?

**Comment by Master92** [comment]
@evilC I'd be okay with that as well 😉👍

**Pull request merged**
