### PR TITLE
support Low band and (540P60)17Mhz

### PR DESCRIPTION
**Pull request by ligenxxxx**
- Set HDZero Band to Low, you can scan low band.
- Set HDZero BW to 17Mhz, you can scan 540p60.
image

vtx low band is here:
https://github.com/hd-zero/hdzero-vtx/pull/145

### CODE REVIEW

**Comment by ligenxxxx** [comment]
Screenshot from 2023-08-01 19-28-06
Screenshot from 2023-08-01 19-28-39

**Comment by ligenxxxx** [comment]
image

**Comment by HazzaHFPV** [comment]
At the top it says it supports now 1080P100.
This does not work, gives a blank or green screen.

**Comment by ligenxxxx** [comment]
> At the top it says it supports now 1080P100. This does not work, gives a blank or green screen.

I made a mistake, it should be 1080p50. I have corrected it.

**Comment by HazzaHFPV** [comment]
Ah ok :) yes, 1080P50 works flawlessly and smooth :)

**Comment by HazzaHFPV** [comment]
Another report to this: I have the impression that the 1080P30 HDZero mode is still shown as 720p in the goggles. I see aliasing along the edges of objects and the OSD is aliased as well. DVR recording looks fine, but when compared to the live feed in the goggles, the goggles show less sharpness/aliasing which makes me think that the live image is still being downscaled.

**Pull request merged**
