### PR TITLE
Head Tilt Alarm

### PR DESCRIPTION
**Pull request by IDV7**
I was having issues with looking at the ground, so decided to create a feature that lets you select an angle at which it should start beeping.

I made a sub page in the head tracker page for the alarm. 
You can choose to turn the alarm off, put it in video mode where it will beep when you have signal, or in arm mode where it will beep when you are armed (this is using ELRS backpack Rec packet to see if the quad is armed or not.)
The set tilt alarm option is where you select at what angle you want it to start beeping, just hold your head at that angle and click the button.

image

### CODE REVIEW

**Comment by kevinsumner** [comment]
I was just considering building a head tilt alarm from, e.g., an Arduino. I'd probably use this instead.

One future feature I'd like is something like a warning threshold, where at, say, 5-degrees before hitting the alarm threshold, a much quieter and less intrusive warning sound starts. The idea is to provide some gentler feedback before the fairly alarming `beep()`. I'm not sure what the options for a less loud noise would be, though.

**Comment by kevinsumner** [comment]
Also, @IDV7, you didn't mention your demo video, but I found this PR from there originally, so I'm linking it here in case folks find this PR first: https://www.youtube.com/watch?v=1fqnTGYG2Xg

**Comment by IDV7** [comment]
> Also, @IDV7, you didn't mention your demo video, but I found this PR from there originally, so I'm linking it here in case folks find this PR first: https://www.youtube.com/watch?v=1fqnTGYG2Xg

Reason being that that video is outdated, the gui has been updated. 



> I was just considering building a head tilt alarm from, e.g., an Arduino. I'd probably use this instead.
> 
> One future feature I'd like is something like a warning threshold, where at, say, 5-degrees before hitting the alarm threshold, a much quieter and less intrusive warning sound starts. The idea is to provide some gentler feedback before the fairly alarming `beep()`. I'm not sure what the options for a less loud noise would be, though.

To me its not that annoying/loud. But could think about it. What I probably will do is make an option for a visual warning / both.

**Comment by kevinsumner** [comment]
> option for a visual warning / both

I like that.

**Comment by IDV7** [comment]
@kevinsumner if you would like to test it out / use it already check: https://github.com/IDV7/hdzero-goggle/actions/runs/7660900052

**Comment by HazzaHFPV** [comment]
any chance to implement this with a kind of artificial horizon as OSD?

**Comment by IDV7** [comment]
> any chance to implement this with a kind of artificial horizon as OSD?

I was thinking of a visual warning, but I don't really get the use case of a artificial horizon, can you elaborate?

**Comment by IDV7** [comment]
@HazzaHFPV > any chance to implement this with a kind of artificial horizon as OSD?

I was thinking of a visual warning, but I don't really get the use case of a artificial horizon, can you elaborate?

**Comment by Schlaegel** [comment]
An artificial horizon would be intuitive. Even if it was just a little symbol on the side of the screens. When I tilt my head down, the horizon marker goes up  from the middle. It would be visual feedback in the way we usually see visual feedback for nodding.

**Comment by HazzaHFPV** [comment]
> @HazzaHFPV
> 
> > any chance to implement this with a kind of artificial horizon as OSD?
> 
> I was thinking of a visual warning, but I don't really see the use case of an artificial horizon, can you elaborate?

..sorry for replying to this so late, I fell ill and only just booted up my PC for the first time in over a week.

For me personally, it would be great to have a visual indication of the angle of my head relative to the horizon or relative to the angle I am aiming for. Or a numerical indication in the Goggles OSD that shows the deviation of the targeted head angle.

Say I am aiming to look up 20° as that will be the flight path away from me. I would set that angle as the setpoint for the head tilt indicator and in the OSD it then would show the offset from that. So if my head is on target is says 0°, if my view drifts down it would indictate the appropriate negative angle, -10° for example, and positive deviation if I look further up.
My initial thought was to look straight, center the head-tracking for looking straight and then have a visual indication in form of a line deviating from the center (0°, horizontal) to show the angle one is looking at.

I am no programmer so maybe that idea, either just numerical goggle OSD element or the horizon-style indication is too much of a pain to implement? Just an idea :)

As the goggle can give out the pwm signals from the head tracker, one can probably also programme a precisce audio feature into an edgetx/opentx radio to give out callouts of the angles according to the pwm signals. Or just show the value of the relevant RC-Channel in the Betaflight OSD: in that case you just have to remember the value of the channel that corresponds to head-angle you are aiming for...

**Comment by IDV7** [comment]
> > @HazzaHFPV
> > > any chance to implement this with a kind of artificial horizon as OSD?
> > 
> > 
> > I was thinking of a visual warning, but I don't really see the use case of an artificial horizon, can you elaborate?
> 
> ..sorry for replying to this so late, I fell ill and only just booted up my PC for the first time in over a week.
> 
> For me personally, it would be great to have a visual indication of the angle of my head relative to the horizon or relative to the angle I am aiming for. Or a numerical indication in the Goggles OSD that shows the deviation of the targeted head angle.
> 
> Say I am aiming to look up 20° as that will be the flight path away from me. I would set that angle as the setpoint for the head tilt indicator and in the OSD it then would show the offset from that. So if my head is on target is says 0°, if my view drifts down it would indictate the appropriate negative angle, -10° for example, and positive deviation if I look further up. My initial thought was to look straight, center the head-tracking for looking straight and then have a visual indication in form of a line deviating from the center (0°, horizontal) to show the angle one is looking at.
> 
> I am no programmer so maybe that idea, either just numerical goggle OSD element or the horizon-style indication is too much of a pain to implement? Just an idea :)
> 
> As the goggle can give out the pwm signals from the head tracker, one can probably also programme a precisce audio feature into an edgetx/opentx radio to give out callouts of the angles according to the pwm signals.
> 
> Or one can just display the value of the relevant RC-Channel in the Betaflight OSD: in that case you just have to remember the value of the channel that corresponds to head-angle you are aiming for...

It would for sure be possible to put the angle in the hdz osd, but at the moment I don't really have the time. I might look into it in the future.

**Pull request merged**
